version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: yotur/kittygram_backend
    env_file: .env
    volumes:
      - media:/app/media
      - static:/app/backend_static
    depends_on:
      - db 
  frontend:
    env_file: .env
    image: yotur/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: yotur/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - frontend
      - backend
